### ISSUE TITLE
research document collection

### ISSUE THREAD

**Issue by derekeder** [datamade/just-spaces#1]
Documents mentioned by folks from our Philly trip:

* [x] Melissa Kim - Said she'd share the presentation about the "Equity Maturity Model"
* [ ] Jaime Gauthier - Said she'd share the survey that they use when they conduct workshops for "friends of" groups
* [ ] Jaime also mentioned that she could share the surveys that they did when they were doing their "civic commons" work (might be interesting to see the results, too)
* [ ] Jaime and Allison also mentioned that there is a form that they use for new "friends of" groups to register. this might be interesting to see only because they are required to meet certain criteria (but is honestly less interesting than the other two). i couldn't find it on their website. Maybe there's a PDF version?
* [x] Clark Park Report (Andrew UCD)

Collect these in our Google Drive folder: https://drive.google.com/drive/folders/19lPvqBMwg_O52HOVbydnNugJVDmzmk6Z

**Comment by derekeder** [comment]
@beamalsky @evz if we hear of other docs, add them here.

**Comment by beamalsky** [comment]
The "Equity Maturity Model" from Melissa Kim: http://equitymaturity.com
