### ISSUE TITLE
Create geographic widget for selecting CensusAreas

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#101]
Create a form widget allowing a user to select a group of census tracts or blocks to create a CensusArea. The widget should:

- Display all available Census blockgroups on a map
- Allow the user to select, deselect, and clear multiple blockgroups from the map
- Save the blockgroups to `CensusArea.fips_codes`

We built out some prior art for this kind of "geographic multiselect" in EDI. See: 
- https://github.com/datamade/erikson-edi/blob/ad68b7853b967be3e1adc3cf6330b8c5e63218fb/edi/forms.py#L59-L68
- https://github.com/datamade/erikson-edi/blob/ad68b7853b967be3e1adc3cf6330b8c5e63218fb/edi/widgets.py#L9-L53

**Comment by beamalsky** [comment]
Would you be up for including help text on Census Areas and how to use them in this PR?

**Comment by jeancochrane** [comment]
I think help text might make more sense in #177, since the help text will primarily be a part of the views and not the widget, right?

**Comment by beamalsky** [comment]
We'll need help text describing how to use the widget as well as help text explaining how census areas are defined and how to use them, both of which I think you're better positioned to write.

**Comment by jeancochrane** [comment]
Gotcha. I'm still not sure that text will make sense in the context of this PR, but I'm happy to take responsibility for making sure it gets incorporated once we wire the widget and the models together.

**Comment by beamalsky** [comment]
Sounds good!
