### ISSUE TITLE
Create preset intercept survey questions

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#104]
Create Fobi form elements for "preset" questions corresponding to common intercept questions that we think UCD will want to ask often, including:

- How old are you?
- What's the closest street intersection to where you live?
- What gender do you most identify with?
- What income group does your household fall under?
- What is your highest formal degree of education?
- Which race or ethnicity best describes you?
- What is your current emplyoment status?
- How many years have you lived at your current address?
- Are you a homeowner or a renter?
- How did you travel here?

These questions all correspond to questions in the Clark Park survey. Use those questions for reference on the appropriate options that should be available.

I'll follow up with Tyler to see if there are any more questions we should include.

Creating these preset questions will allow us to tie intercept surveys to ACS data as described in https://github.com/datamade/just-spaces/issues/78#issuecomment-483411198.

**Comment by jeancochrane** [comment]
These questions got the sign-off from Tyler, so we can start development.

**Comment by beamalsky** [comment]
@jeancochrane let's figure out what the input fields should look like for each of these. Here are my best guesses, could you look them over? For the preset dropdowns, I'm thinking they should line up with ACS buckets. 

- [ ] How old are you? **Integer**
- [ ] What's the closest street intersection to where you live? **Not sure about this one**
- [ ] What gender do you most identify with? **Text input? Dropdown with preset choices? Dropdown with choices set by survey creator?**
- [ ] What income group does your household fall under? **Dropdown with preset choices**
- [ ] What is your highest formal degree of education? **Dropdown with preset choices**
- [ ] Which race or ethnicity best describes you? **Text input? Dropdown with preset choices? Dropdown with choices set by survey creator?**
- [ ] What is your current employment status?  **Dropdown with preset choices**
- [ ] How many years have you lived at your current address? **Integer**
- [ ] Are you a homeowner or a renter? **Dropdown with preset choices**
- [ ] How did you travel here? **Dropdown with preset choices**

**Comment by jeancochrane** [comment]
These look great to me! A few thoughts:

> What's the closest street intersection to where you live?

Let's skip this one for now. We can circle back on it when we implement #81.

> What gender do you most identify with?

This will need to be a dropdown in order to compare to ACS data. I'd start with the categories UCD used in their [Clark Park report](http://rpubs.com/tylerjtran/moviesSurvey2018#gender-identity):

> At the first movie night, 58 (30%) respondents identified as male, 110 (56%) as female, and 6 (3%) as non-binary. 22 respondents did not answer the question.

This will require a little extra care on the DAD side to handle the options that aren't present in ACS, but I think it's worth it.

**Comment by beamalsky** [comment]
Great! That makes sense to me. Would you be up for filling in the dropdowns of the others to match up with ACS data? Feel free to edit that comment directly. I'll get started on the ones that are set tomorrow!

**Comment by jeancochrane** [comment]
Sure thing :+1:

**Comment by beamalsky** [comment]
Actually @jeancochrane could you put those into the PR for this? https://github.com/datamade/just-spaces/pull/119

**Comment by jeancochrane** [comment]
Yup! I'll flesh that out first thing tomorrow morning.

**Comment by beamalsky** [comment]
Closed by #119 !
