### ISSUE TITLE
Create common groupings of PLDP form questions

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#105]
Related to #104, create common groupings of observational PLDP questions. For example, right now we recommend that the user create form elements for "male," "female," and "unknown" when observing the gender of participants, but we don't have a way to quickly allow the user to implement that pattern, and leaving it up to the user means that our ACS comparisons in #100 may not be complete if the survey designer doesn't design the question properly.

This might be a tricky code design task, since I doubt Fobi supports this feature out of the box.

**Comment by beamalsky** [comment]
Closed by #117 !
