### ISSUE TITLE
Survey tool: Create (initial implementation)

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#11]
The survey backend tool will have up to six different views for creating a survey. This initial version will focus on creating a survey from a template:

1. Select survey creation mode: the user selects the mode of survey creation (copy existing survey; **start from a template;** build survey from scratch)
2.  Select survey type: the user selects which template (intercept vs. observational)
3. Build the survey: the user builds the survey

@beamalsky we can break this into smaller issues, if that makes sense to you. Let's check in about this, after you start work on this part of tool.

***

**Feedback from UCD:** be sure to include questions with radio buttons (for true vs. false; single selection) and checkboxes (for multiple selection)

**Comment by reginafcompton** [comment]
I am thinking about location data in relation to the PLDP, and more and more, I see the complexity of this aspect. Another question that occurs to me: do we want to give users the option to select the location of the survey, during the survey creation process? currently, it seems like location data gets entered during the run phase, but I can see why someone would want to describe the survey location, as they are creating a survey with a specific space in mind.

**Comment by beamalsky** [comment]
Now that I've wrapped my head around the PLDP, I see there are two kinds of location data we need to handle:

1. The location models [described in the protocol](https://github.com/datamade/django-pldp/blob/model-setup/pldp/models.py#L59-L224). These will be attached to studies before an individual survey is run, and describe where it is taking place. I'm thinking this means there needs to be a location creation interface, or we need to add these manually for UCD so they can select one when creating a new study.

2. Location data entered as part of a survey, eg (maybe primarily) in answer to the questions, "Where do you live?" We've discussed building something to let people put in their intersection to give us block-level data, and we should also probably be able to handle zip codes.

**Comment by reginafcompton** [comment]
@beamalsky started this issue, but will complete it next week. I'll place the issue in the appropriate milestone.

**Comment by beamalsky** [comment]
Some discrete subtasks to talk about tomorrow:

- [ ] Figure out which premade plugins (eg boolean, radio button, short answer) we want to include. Exclude others. Evaluate if there are generic question types missing that we should implement
- [ ] Create custom PLDP plugin
- [ ] The Clark Park survey has a "other ______" option for radio and select multiple options. Should we implement this? Maybe a question for UCD once they've seen it in action.

**Comment by reginafcompton** [comment]
@beamalsky yes, I think we should ask UCD about the "other ______" option, before implementing it and after we send them our first version of the tool.

**Comment by beamalsky** [comment]
Agreed! Today I'm working on the PLDP plugin with the aim of getting it into a PR for your review tomorrow.

**Comment by reginafcompton** [comment]
Closing! I'll break next steps into smaller issues.
