### ISSUE TITLE
Remove passphrase from GPG key on the staging server

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#112]
The staging server is failing to deploy because the GPG key has a passphrase. Either A) remove the passphrase from the key, or B) create a new key without a passphrase and update the Blackbox config to use the new key.

**Comment by beamalsky** [comment]
Figure out: does the [deploy-a-site Makefile](https://github.com/datamade/deploy-a-site/blob/master/examples/gpg-key.mk) always create a key with a passphrase? If so, that should change.
