### ISSUE TITLE
Data modeling for surveys - Technical spec

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#13]
Before we can realize the wireframes, we need to determine which parts of the PLDP will inform the Just Spaces data models/forms, particularly for the survey. 

@beamalsky - I'd like to prioritize this for next Monday, after we've had time to ingest `django-pldp`. Does that make sense?

**Comment by beamalsky** [comment]
Started a doc for this: https://docs.google.com/document/d/1TONNkmYgKKJJSvHdFLvZpClK5dc20V5WkVnXdpsrHRQ/edit#heading=h.sgwndrk5ct5j

Reference from CSH: https://docs.google.com/document/d/1LKxmd0gwfI3tLYudLS3oBQnL78xFZckFfJ-8NAdQlc4/edit#heading=h.gszm8rvyiqj0

**Comment by reginafcompton** [comment]
We have a plan! Closing this.

(Also, I setup Fobi locally, and it's pretty slick @beamalsky)
