### ISSUE TITLE
Automatically select user on survey creation

### ISSUE THREAD

**Issue by beamalsky** [datamade/just-spaces#140]
The top field here should grab who's logged in and autofill:
<img width="864" alt="Screen Shot 2019-05-21 at 3 54 37 PM" src="https://user-images.githubusercontent.com/1094243/58130093-d6e91100-7be0-11e9-9716-5a89d8fc50db.png">

I can't think of a case where the current user isn't the one who should be saved.

**Comment by jeancochrane** [comment]
Perhaps we could hide the `User` field when we prepopulate it? I think you're right that there's no case where the current user isn't the right one, but also I don't think we want to allow a user to claim that another user created a survey.

**Comment by beamalsky** [comment]
I think you're right!
