### ISSUE TITLE
Get our terminology in line with the PLDP

### ISSUE THREAD

**Issue by beamalsky** [datamade/just-spaces#16]
The PLDP has separate models for survey and study, which I think we should start using in `just-spaces` and also in our internal planning language:

1. Study: A project undertaken by an agency with a specific area and a start and end date. A study consists of many surveys. 
2. Survey: A collection of components (survey questions) with attached context data (start time, end time, exact location, weather, etc.)

So, an admin user would create a study and then create surveys within that study. @reginafcompton does this make sense to you? It implies some changes to the wireframes that it might be helpful down the line for me to put in.

**Comment by reginafcompton** [comment]
@beamalsky yes, this makes sense: I think we've thus far been overlooking the concept of a study. 

Will we require all surveys to belong to a study?

**Comment by beamalsky** [comment]
That's the way PLDP is set up, so yes—surveys are linked to agencies through study.

**Comment by reginafcompton** [comment]
Okay, I think we can implement PLDP, strictly....at first. But I can imagine users wanting to create a one-off survey, without attaching it to a study, i.e., topically grouped surveys. 

Is this an possible to divergence from PLDP? And if you think so, should we track it somewhere (with others, like fields for gender)?

**Comment by beamalsky** [comment]
I'm wondering if we could have a base study for each agency that acts as the "no study" option—ie, make location and start/end dates unrequired, and automatically create a generic study with each agency that's ready to use. Potentially a little hacky, but would let us stick to the PLDP while maintaining user flexibility!

**Comment by reginafcompton** [comment]
oh, that could work!

**Comment by beamalsky** [comment]
I think we've accomplished this. @reginafcompton do you think this is ok to close?

**Comment by reginafcompton** [comment]
yes!
