### ISSUE TITLE
Create CRUD views for CensusAreas

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#177]
Add Create, Read (i.e. List), Update (i.e. Edit), and (soft) Delete views for CensusArea objects. Similar to Locations, additionally update the "Compare to Census" question in the DAD prompting the user to create a geography if they don't see one they want.

For the scope of this issue, the Create and Edit views need only add/update the `CensusArea.name` attribute. (The geographies themselves should be added in #101.) The List view should show the name of the CensusArea in addition to a thumbnail map so that the user can quickly scan to get a rough sense of what boundaries the CensusArea are.

**Comment by beamalsky** [comment]
I could also take this on if it makes sense!
