### ISSUE TITLE
ACS charts can choose the same color as primary_source

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#188]
Occasionally when adding or removing a CensusArea from a chart, the DAD will choose the same color for the ACS layer as the `primary_source`:

![image001](https://user-images.githubusercontent.com/14170650/60376191-d2c7c480-99d2-11e9-8dae-a81a27d90930.jpg)

I'm guessing this is because Highcharts only knows the colors of the series that it's adding at a given time, and not necessarily the series that have already been added.

See if there's a way we can override this behavior to instruct Highcharts not to use colors that have already been displayed on the chart.

**Comment by beamalsky** [comment]
Don't spend more than 2 hr fixing this!
