### ISSUE TITLE
Detail view of collected data: Discuss additional features

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#19]
This particular element of the tool may require further brainstorming. The below describes some aspects to consider. @beamalsky - let's use this issue to identify additional features to include. Then, we can open smaller discrete issues.

## Data export 

Users should be able to export the data as a CSV file. Depending on our solution [here](https://github.com/datamade/just-spaces/issues/25), we may build this functionality "from scratch," i.e., without the use of fobi.

## Table: Searchable? Sortable? Filters?

To what extent should users be able to explore the survey data, as presented in a table? The table could be searchable and sortable. We could also include simple filtering, e.g., by date. 

## Visualizations

Certain types of data can be automatically displayed in generic visualizations. Let's determine what's possible!

## Pushing collected data to the public interface

[Our notes from the wireframes meeting](https://docs.google.com/document/d/1NjPvpypfwIfbbPn0bws9-BSXOgZG96cjcmS4PcSThtE/edit) document some of the elements that need further conversation. Notably, we are waiting to hear a response from the stakeholders about a couple lingering questions. From Feb 5 email:

> _On presenting survey results to the public_

> We need to think about how the public will access data collected in surveys, if at all. Should we push to make all survey results public? There may be circumstances when we'd want the data to be private, including having too few respondents or when the surveys contain sensitive questions. Here's a few additional questions to chew on:

> * Will all data be public by default? In this case, how should we allow survey creators to opt out of their data being public?
> * Who should have the ability to make data public?
> * What kinds of sensible default settings would make sense here?

**Comment by beamalsky** [comment]
In terms of how to structure the table and CSV download, I think we should follow the exampel of the sample data from the PLDP repo: https://github.com/gehl-institute/pldp/tree/master/Sample%20Data

**Comment by jeancochrane** [comment]
Superceded by #78.
