### ISSUE TITLE
Write up some open source copy

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#198]
For the About page content, write up a short paragraph about the open source nature of the project.

**Comment by jeancochrane** [comment]
Here's my stab at a draft:

> Just Spaces is open source under the [MIT license](https://github.com/datamade/just-spaces/blob/d944088b9ff1b36fa4ead40e6036e69538046d69/LICENSE), which means that the code that powers the site is freely available for all to use without restriction. If you'd like to tinker with the code, or even stand up your own version of Just Spaces, you can fork the code at https://github.com/datamade/just-spaces and follow the setup instructions in the README. The code for Just Spaces was written by [DataMade](https://datamade.us/) using a number of other open source tools, including Python, Django, and PostgreSQL.

**Comment by beamalsky** [comment]
Looks great to me! To avoid a fourth use of "code" I'd just change this phrase: 

>If you'd like to tinker with the code, or even stand up your own version of Just Spaces, you can fork the **repository**

Once DataMade has a new mission statement we could suggest including that after this paragraph on the About page!
