### ISSUE TITLE
user research report

### ISSUE THREAD

**Issue by derekeder** [datamade/just-spaces#2]
User interviews & notes:

* Setha Low: https://docs.google.com/document/d/1Un2M_q7Vweq9bVkNdkwX45UtGYOBll8LvjRk_7J3D-Y/edit
* UCD staff: https://docs.google.com/document/d/1jeL0q1RYk3OX7obnU19ZyScpIvEywPxyykqyMyebnSY/edit
* Philly meetings: https://docs.google.com/document/d/1572LS-we7lnEDNWGvRrYz69v-CpuiJ9dzhhgRkN3GaM/edit#

**Comment by derekeder** [comment]
This report can be modeled after the one we wrote for Risk & Reach: https://github.com/datamade/risk-and-reach/issues/1

**Comment by beamalsky** [comment]
Starting the doc: https://docs.google.com/document/d/1XBhw7CJ7tJJ_XxCe3VLQ9ZAigZPFwLkvuvwSSnv8v94/edit

**Comment by beamalsky** [comment]
Report is sent! We are going to set up a meeting with UCD to discuss once we've also sent wireframes (#4)

**Comment by beamalsky** [comment]
@reginafcompton I think this can be closed

**Comment by reginafcompton** [comment]
that's right! closing.
