### ISSUE TITLE
Run Survey table breaks container on small screens

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#202]
This is likely an issue with the `table-responsive` class not being set properly (IIRC this can happen if you set it on the `table` itself rather than the containing `div`):

![IMG_1150](https://user-images.githubusercontent.com/14170650/61088956-343e5900-a3ff-11e9-9ea6-5de608b1646a.jpg)

**Comment by beamalsky** [comment]
Wow this really explains why `table-responsive` has never worked the way I thought it should, ha! Great catch, thank you.
