### ISSUE TITLE
Initial front end design work

### ISSUE THREAD

**Issue by beamalsky** [datamade/just-spaces#22]
Start front end design work for part 3 views: survey creation, editing, and running.

Potentially also location and study creation.

**Comment by beamalsky** [comment]
To do for this initial round of design work: 
- [ ] Get sidebar collapsing on mobile
- [ ] Sensible icons

**Comment by reginafcompton** [comment]
We'll open an issue for mobile optimization (for later), and another issue for finessing the front end (for next week).
