### ISSUE TITLE
RESTful-ish routes

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#26]
We should aspire to have our URL patterns follow (as closely as reasonable) RESTful conventions. 

### Surveys – ListView
RESTful urls should identify a resource. The url should fetch a particular kind of resource (e.g., published vs. unpublished) with query params. [(See point 8.)](https://medium.com/hashmapinc/rest-good-practices-for-api-design-881439796dc9)

List view of surveys that can be edited (replaces “edit-survey”)
`/surveys?state=unpublished`

List view of surveys that can be run (replaces “run-survey”)
`/surveys?state=published`

With this, views.py should have a SurveyListView, rather than EditSurvey and RunSurvey. The view should check for query params, and return a filtered Survey queryset.

### Surveys – EditView, CreateView, DetailView (from Fobi)
django-fobi comes with RESTful-ish routes. The ones that currently apply to our tool:

`/fobi/forms/create`

`/fobi/forms/edit/{form-id}/`

`/fobi/view/{form-slug}/`

I’d like to see these modified to match the Just Spaces naming conventions, if possible:

“/fobi/forms/create” becomes “/surveys/create”
“/fobi/forms/edit/{form-id}/” becomes “/surveys/edit/{survey-id}”
“/fobi/view/{form-slug}/” becomes “/surveys/{survey-id}”

### Other views
We also have CreateAgency, CreateLocation, and CreateStudy. I’d suggest making the urls (urls.py) a touch more RESTful, so that:

“/create-agency” becomes “agencies/create”
“/create-location” becomes “locations/create”

I don't think we are going to have list and detail views for location, agency, and study. Do you agree, @beamalsky?

**Comment by beamalsky** [comment]
Thank you for this, and I do agree! I think there's are future conversations to be had about if/how UCD should be able to edit and delete agencies and locations, but for now I'll get on implementing these.

**Comment by reginafcompton** [comment]
We have a strong start on RESTful routes via PR #17! 

We need to decide how the tool should distinguish between surveys-to-edit and surveys-to-run: then, we can filter via query params, as described in my first comment above.

**Comment by reginafcompton** [comment]
I moved the list view part of this issue to https://github.com/datamade/just-spaces/issues/32. Closing this!
