### ISSUE TITLE
Populate database with Clark Park and Porch survey examples

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#29]
Create Clark Park and Porch surveys (using the current interface). 

This may require adding more form elements, so the surveys can reflect PLDP.

**Comment by beamalsky** [comment]
Fields from the PLDP survey model that should eventually be implemented as form elements:

- [ ] location
- [ ] study
- [ ] time_start _use default time plugin to start_
- [ ] time_stop _use default time plugin to start_
- [ ] time_character _use default text plugin to start_
- [ ] representation _use default dropdown plugin to start_
- [ ] microclimate _use default text plugin to start_
- [ ] temperature_c _use default temp (?) plugin to start_
- [ ] method _use default dropdown plugin to start_

**Comment by beamalsky** [comment]
Update: Clark Park and Porch surveys are built out on https://justspaces.datamade.us/ as examples! This should give us a good tool to talk through next steps with UCD. In particular, I'd like to talk to them about how closely they'd like to stick to the PLDP. I didn't end up needing to implement any of the above form elements for these sample surveys.
