### ISSUE TITLE
March 12 meeting with Gehl Institute

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#30]
Our email to UCD describes the aim of this meeting:

> "we've been thinking more about the Public Life Data Protocol and which of its aspects might benefit from adjustment.
> 
> We think it would be worthwhile to start a conversation with the Gehl Institute about our work. They may be interested in accepting some of our adjustments in the official PLDP, and we'd prefer to start that dialogue sooner rather than later (they may also not be interested, which would be useful for us to know)."

***

Before March 12, let's put together an agenda that, among other things, outlines some of the changes to the PLDP we've already implemented.

**Comment by beamalsky** [comment]
We did this and followed up! @reginafcompton I think this can be closed.

**Comment by reginafcompton** [comment]
Yes it can!
