### ISSUE TITLE
Browser-side form validation

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#31]
We brought up this issue in a previous PR: https://github.com/datamade/just-spaces/pull/17#discussion_r258528489

Let's plan to revisit this, as the survey form takes shape.

**Comment by beamalsky** [comment]
We should also make sure all forms have good error rendering! See this thread on [error text in our CreateSurvey form](https://github.com/datamade/just-spaces/pull/56#discussion_r267395674).
