### ISSUE TITLE
Make a plan for handling user permissions

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#48]
Different users will have different levels of access to the site. We need to concretize this hierarchy before implementation. 

- [ ] Email UCD, and remind them to think about this (as a follow up to our March 11 meeting)
- [ ] Perhaps, have another phone call about this.
- [ ] **Put into writing** the exact specifications of user permissions – both UCD and DataMade need to agree on these specifications.

**Comment by beamalsky** [comment]
For now, everyone is a superuser. This will need to change! I've turned off Fobi's permissioning system because I think we're better served building our own.

**Comment by beamalsky** [comment]
I propose we set up either 2 or 3 types of users:

1. **Users:** The lowest level of permissions. Users can run surveys to which they've been granted access.
2. **Admins:** The middle level of permissions. Admins can run surveys as well as create, edit, and delete Studies, Study Areas, Surveys, and Locations. They can grant Users access to surveys. Admins can also view collected data and design data visualizations on the collected data pages.
3. **Superusers:** The highest level of permissions. In addition to the permissions of Users and Admins, Superusers can create, edit, and delete Agencies and other accounts.

New accounts are created as users, and can be promoted to Admins or Superusers by Superusers. I'm still thinking on this, and it might make sense to squash 2 and 3 and pitch UCD with just two levels—Users and Admins—and figure out if there's a need for more differentiated roles from there.

**Comment by beamalsky** [comment]
Plan approved by UCD! See #173
