### ISSUE TITLE
Send follow-up email re: March 11 meeting

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#49]
We had a productive feedback session with UCD today! We have two points on which to follow up:

- reevaluating PLDP’s metadata (@beamalsky will take the lead on this and collect some examples)
- remind UCD to think more about permissions
- introduce @jeancochrane !

**Comment by beamalsky** [comment]
Thinking through metadata in advance of our checkin tomorrow, here are the survey context fields required by the PLDP:

- location
_these are their own models, and will need their own interface to add_
- study
- time_start 
- time_stop
_do we want to automatically record when a survey is opened and when it's submitted?_
- survey_representation
- survey_method

Other survey context fields:
- survey_time_character
- survey_representation
- survey_microclimate 
- survey_temperature_c
- survey_surveyor_name 
_can default this to user_
- survey_notes

Now that we're thinking of observational and intercept surveys more separately, I see a path forward that includes having these each as custom elements and a templated PLDP starter survey that includes them all. I think we should ask UCD if it makes sense to them to require the above required fields in Just Spaces, and if there are automatic initial value they'd like to assign for any. Still thinking this through, but input is welcome!

**Comment by reginafcompton** [comment]
@beamalsky - I forgot where we landed on this: do you want me to draft the email, and put your about notes into something easily ingestible and a place where we can collaborate (e.g., a shared Google doc)? Or are you going to take the lead on that?

**Comment by beamalsky** [comment]
In starting to put the above line of thinking into some succinct questions for UCD, I'm feeling it would be helpful to get further along in implementing the branched survey creation path (observational vs. intercept). What do you think about following the PLDP strictly for now in the observational surveys and minimally in the intercept surveys, noting that departure from the protocol for required metadata fields should be a conversation with UCD in the future, and following up to simply thank them for their time and let them know that we'll be following up with proposed permission groups in the near future?

**Comment by reginafcompton** [comment]
"following up to simply thank them for their time and let them know that we'll be following up with proposed permission groups in the near future".....I think this sounds great @beamalsky. I can draft that and send it to Derek, today.

**Comment by reginafcompton** [comment]
Done!
