### ISSUE TITLE
Identify public data sources for the public-facing site

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#51]
We will spend some time identifying outside data best suited for the public-facing analyses. 

***

### Initial notes

**American Community Survey**
https://censusreporter.org/

- Race (which can be tricky)
- Age and Sex
- Children
- Employment 
- Income
- Poverty
- Public Assistance
- Tenure (owner/renter occupancy status)
- Year move-in
- Vacancy/occupancy
- Educational attainment
- Primary commute mode (possibly useful for comparing to how people arrived at events)

**LODES**

A collaboration between state tax agencies and Census – gives emphasis to employment data. 

Could be useful for analyzing spaces used largely by people who work in the area, rather than people who live nearby (e.g., the Porch). 

Limitations: 

- out-of-date (the current release comes from 2015)
- missing certain federal level workers (from Eric: “I looked at the area around The Porch and it would seem that none of the IRS workers are included”) 
- from Eric” only includes people that have jobs (so, if you're examining the residence side of things, the only people that will be included are people who have jobs).”

**Comment by jeancochrane** [comment]
Here's a first pass at data sources that I'd like to see. My general approach was to take each item in the PLDP and find data for that item that might provide important context. In addition, I created a `Misc` category for data that don't correspond to anything directly in the PLDP but that strike me as important.

A **bold question mark (?)** indicates data that I know to exist, but that I wasn't able to track down. Perhaps someone else can help shed light on these.

All data are available at the **block group** resolution, unless otherwise noted.

- **Gender**
    - Sex by Age ([Census](https://censusreporter.org/tables/B01002/))
- **Age**
    - Median Age ([Census](https://censusreporter.org/tables/B01001/)) 
- **Income**
    - Median Income by Sex by Work Experience With Income ([Census](https://censusreporter.org/tables/B19326/))
    - Gini Index of Income Inequality ([Census](https://censusreporter.org/tables/B19083/))
- **Mode of transit**
    - Means of Transportation to Work ([Census](https://censusreporter.org/tables/B08301/))
    - Walkability Index ([Data.gov](https://catalog.data.gov/dataset/walkability-index))
    - Transit stops by lat/lng ([SEPTA Open Data](http://septaopendata-septa.opendata.arcgis.com/search))
- **Groups** 
    - Household Type by Household Size ([Census](https://censusreporter.org/tables/B11016/))
    - Population density (**?**)
- **Activities**
    - Usual Hours Worked Per Week ([Census](https://censusreporter.org/tables/B23022/))
    - Breakdown of how leisure time is spent (**?**)
- **Misc** 
    - Land use by parcel ([Phila.gov](http://metadata.phila.gov/#home/datasetdetails/5543864420583086178c4e74/?view_219_sort=field_15|asc))
    - Race ([Census](https://censusreporter.org/tables/B02001/))
    - Hispanic or Latino Origin ([Census](https://censusreporter.org/tables/B03003/))
    - Gini index of racial diversity (we created this for Crain's Book of Lists 2017 by doing some simple math on Census tables. That used to live at [`datamade/book-of-lists`](https://github.com/datamade/book-of-lists), but I'm seeing a 404 for it now?)
    - Daily or monthly summaries of temp/precipitation by FIPS code ([NOAA](https://www.ncdc.noaa.gov/cdo-web/datasets))

My first reaction is that this is probably too much data. What do you think @reginafcompton @beamalsky? Anything here we can leave out? Or perhaps things that I missed?

**Comment by reginafcompton** [comment]
Terrific work! I think using the PLDP as a guide works well. (N.b., I adjusted a couple inaccurate links – that's why it says "edited by regina..." above.)

### Additions
Too much data? That's not my initial reaction. We're designing an import process for census data: I see no reason to be ungenerous with that particular data source. 

In fact, I'd like to see us pull in data about [educational attainment from Census](https://censusreporter.org/search/?q=education), since Tyler from UCD flagged that as something they might like to include. [Tenure by Educational Attainment of Householder](https://censusreporter.org/tables/B25013/) could be meaningful.

### Possible omissions 
With that said, I think we should try to minimize the amount of data _sources_ and also focus on data with obvious PLDP equivalences. I'd probably omit: 
* Daily or monthly summaries of temp/precipitation by FIPS code (NOAA)
* Land use by parcel (Phila.gov)

Do we know about the ease-fulness of importing data from SEPTA? I think we could do something with transits stops data noted above, but if it proves hard to get, then we could omit that too.

### Other notes

Did `book-of-lists` end up in bitbucket? Let's check with @derekeder. 

For population density, could we use the ACS: https://catalog.data.gov/dataset/census-block-groups-by-population-density-2012-acs?

**Comment by jeancochrane** [comment]
> In fact, I'd like to see us pull in data about educational attainment from Census, since Tyler from UCD flagged that as something they might like to include. Tenure by Educational Attainment of Householder could be meaningful.

I put in a link to [Educational Attainment](https://censusreporter.org/tables/B15003/) above, which gives the raw counts without breaking it down by household type. Let me know what you think about that!

>  I think we should try to minimize the amount of data sources and also focus on data with obvious PLDP equivalences. I'd probably omit:
>
> - Daily or monthly summaries of temp/precipitation by FIPS code (NOAA)
> - Land use by parcel (Phila.gov)

I'll be sad to see Land Use go, but you make a good point. Weather data seems relevant to the PLDP required fields `survey_context.survey_temperature_c` and `survey_context.survey_microclimate` -- if we're reporting those fields, it might be useful to know whether the weather was unseasonably warm/cool or rainy for the area during a survey. But maybe that's not a set of concerns that UCD cares about? Curious what your take is.

> Do we know about the ease-fulness of importing data from SEPTA? I think we could do something with transits stops data noted above, but if it proves hard to get, then we could omit that too.

I've had bad experiences working with SEPTA APIs in the past, mostly around A) undocumented APIs and B) unreliable real-time data. But the data portal I linked above seems to be a big improvement -- it looks like they're using a data portal CMS that makes the data much easier to understand, and it's static data so it shouldn't be too complicated. See e.g. [trolley stops](http://septaopendata-septa.opendata.arcgis.com/datasets/8aee4ea99d564e50b986e99a4669418a_0/data) and [bus stops](http://septaopendata-septa.opendata.arcgis.com/datasets/5c063cd7037547659905ab1761db469e_0).

I say we go for it, and if it turns into a rabbit hole we try to exit quickly. 

> Did `book-of-lists` end up in bitbucket? Let's check with @derekeder.

`book-of-lists` is on GitLab these days; updated the link above accordingly.

> For population density, could we use the ACS: https://catalog.data.gov/dataset/census-block-groups-by-population-density-2012-acs?

This seems promising, but I can't find a corresponding table on [FactFinder](https://factfinder.census.gov/faces/nav/jsf/pages/searchresults.xhtml) or [Census Reporter](https://censusreporter.org/search/?q=population+density). Is this an ACS table, or a special dataset prepared by Montgomery County?

**Comment by reginafcompton** [comment]
Responding in turn!

(1) Climate data: I guess I could see an opportunity for making meaningful comparisons, like, "it's usually sunny in UCD, which might account for x,y,z in the survey data, collected on a rainy day." **At the very least, I think this might be something worth bringing up with UCD.** I am not familiar with NOAA, though. Do you know anything about its usability? 

(2) Yes, I cannot find an ACS table for population density...and the link seems to be just for Montgomery County, and I cannot find a similar one for Philly. Hmmmm. Let's consult with Master Forest on this one.

Everything else looks fantastic. Thanks!

**Comment by jeancochrane** [comment]
> Climate data: I guess I could see an opportunity for making meaningful comparisons, like, "it's usually sunny in UCD, which might account for x,y,z in the survey data, collected on a rainy day." At the very least, I think this might be something worth bringing up with UCD. I am not familiar with NOAA, though. Do you know anything about its usability?

I've used NOAA for weather reports, but never as a source for a data pipeline. Forest may have more thoughts.

> Yes, I cannot find an ACS table for population density... [...] Let's consult with Master Forest on this one.

Agreed!

**Comment by jeancochrane** [comment]
@reginafcompton I took a final pass based on conversations with Forest! You can see my edits if you click on the `edited` link at the top of [this post](https://github.com/datamade/just-spaces/issues/51#issuecomment-474477644).

The changes include:
- Using distributions instead of medians where possible
- Calculating population density by dividing total population by the area of the geography
- Removing leisure time (we may be able to get this at low resolutions, but aren't sure yet, so we shouldn't promise it)

Forest also brought up the good point that we need to help UCD figure out which geographies are appropriate here -- not just so that we know what level of resolution to import, but also so that we can determine how a survey should be linked to a particular geography (e.g. if a survey takes place in Clark Park, what should the "catchment area" be for that survey? A radius of 2 miles? Or perhaps we let the survey designer determine the geography?)

**Comment by reginafcompton** [comment]
Beautiful @jeancochrane ! 

Yes, the question about location has been on our minds, and we discussed it at our February meeting: https://github.com/datamade/just-spaces/issues/60. I think you raise a very useful point: the behavior of our import could help inform how we think about location data collected in surveys (or vice versa). Let's plan to (re)raise this issue with UCD, when we send our initial email about source data.

**Comment by reginafcompton** [comment]
@jeancochrane I think we can close this issue. Is there somewhere else in particular where you'd like to document the sources we plan to import? Or will this issue serve that purpose?

**Comment by jeancochrane** [comment]
I think this issue is as good a place as any! I'll go ahead and close.
