### ISSUE TITLE
Wireframes for public-facing analyses

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#53]
Create wireframes for public-facing analyses (Part 2 of SOW).

We plan to have internal review of these on March 26 and send them to UCD, shortly thereafter.

**Comment by reginafcompton** [comment]
For reference: wireframes for [the survey-builder admin dashboard](https://app.moqups.com/424dLZfkvP/view/page/a8fa2a914?fit_width=1)

**Comment by jeancochrane** [comment]
Just finished up a first draft of frontend wires! Preview here: https://app.moqups.com/424dLZfkvP/view/page/aa5057d0f

**Comment by reginafcompton** [comment]
Very exciting! Thanks @jeancochrane. Looking forward to chatting about these on Tuesday morning. 

cc: @derekeder  and @beamalsky

**Comment by derekeder** [comment]
looking good! added a few comments

**Comment by reginafcompton** [comment]
@jeancochrane fantastic first pass! I really like your initial solution for viewing individual studies (i.e., community profile vs. survey data): I'm really looking forward to our conversation tomorrow and sharing this with UCD.

**Comment by reginafcompton** [comment]
Done!
