### ISSUE TITLE
Come to terms with the PLDP

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#6]
I am going to tidy-up the last bits of this PR: https://github.com/datamade/django-pldp/pull/1

I'll also write some documentation and make sense of how this repo will fit into the Just Spaces project.

I'll be in communication with @beamalsky, e.g., requesting her review, probably talking about things conceptually, etc.

**Comment by reginafcompton** [comment]
Other questions:

* has the Gehl Institute made public version 1.0 (or later)? if so, can we get a copy?
* does the Gehl Institute know about this aspect of the Just Spaces project, i.e., that we're coding out the PLDP as a Django project? It seems like we should be in contact with them about this, in case someone on their team did a similar implementation.

**Comment by reginafcompton** [comment]
@beamalsky - will email UCD today!

**Comment by beamalsky** [comment]
UCD has confirmed that the Sept 2017 Beta release of the PLDP is the right version.

**Comment by reginafcompton** [comment]
We merged [our massive `django-pldp` PR](https://github.com/datamade/django-pldp/pull/1). Closing!
