### ISSUE TITLE
Survey tool: Think about location data

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#60]
Notes from our Feb 5 meeting: 

> _On collecting location information_

>We need to think about how to be precise, but still flexible, when collecting location or address information. We could:

> * Let the browser & device automatically detect their location (e.g., with a “Find me” button). This wouldn't work when collecting respondent home locations while in a public space.
> * Create a way for respondents to select an intersection (e.g., by typing in street names to an input, potentially, visualized on a map) or block level address. 
> * What are some of the best practices we should keep in mind when collecting this information. 
> * Furthermore, do we want to restrict the collection of less useful location information, like zip code?

**Comment by reginafcompton** [comment]
A concrete idea emerged from our conversation with UCD, today! 

The admin dashboard could provide a widget for drawing abstract geometries. In addition, the user could select from preset options, e.g., an entire city or county or particular location.

**Comment by jeancochrane** [comment]
Superceded by #79 and #81.
