### ISSUE TITLE
Detail view of collected data: Initiate and implement a basic table

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#61]
This issue should address:

* setting up view/route for collected data detail view
* presenting survey data in a table

**Comment by reginafcompton** [comment]
@beamalsky - we cannot display data in a table, until we implement a strategy for data handling, right? If so, let's limit the scope of this issue to initiating view/route for the detail view.

**Comment by beamalsky** [comment]
That's right @reginafcompton !

**Comment by beamalsky** [comment]
Closed by #76
