### ISSUE TITLE
Place partials inside `templates/partials`

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#62]
We have a few stray partials that should reside inside a `partials` dir, e.g., sidebar.html. Let's put them where they belong.

**Comment by reginafcompton** [comment]
I looked at several projects, and it appears that, no, we do not treat it as a partial.

**Comment by reginafcompton** [comment]
Is there an argument for treating it as one?

**Comment by beamalsky** [comment]
Closed by #25
