### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#66]
UCD does not have a strong sense of the intended user base for the public-facing site.

@jeancochrane suggested including a "call out" on the public site, i.e., something that invites visitors to contact such-and-such to get more information about the project, specific survey data, etc. This mechanism could help UCD get a better sense of the user base (which could inform future iterations of the project).

**Comment by beamalsky** [comment]
I'm thinking maybe we can return to this concept, since we're not making a public-facing site. Instead of directing users to the login screen immediately upon visiting the site, they could be sent to the site's "About" page with text from UCD about the project.
