### ISSUE TITLE
Create import pipeline for static ACS data

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#67]
While we may eventually want to allow admin users to dynamically import ACS data for custom geographies, most of the data should be statically loaded into the database ahead of time. This includes data at the following resolutions:

- National
- State (PA)
- County (Philadelphia)
- Municipal (Philadelphia)
- Census tract (within Philly)
- Census block (within Philly)

Create an import pipeline for the data outlined in https://github.com/datamade/just-spaces/issues/51#issuecomment-473122287 using:

- GNU Make for extract/transform
- [Census API Python client](https://github.com/datamade/census) for retrieving ACS tables
- Django management command for loading the data into the database

**Comment by fgregg** [comment]
Can we have chat with @hancush and me about this before you do it. We've been thinking on import_data scripts.

**Comment by jeancochrane** [comment]
That sounds like a great idea @fgregg @hancush. I dropped a short call on the calendar for Monday.
