### ISSUE TITLE
Location form

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#81]
Add a widget to the Location form that allows the user to select a geometry. The [GeoDjango OSMWidget](https://docs.djangoproject.com/en/2.1/ref/contrib/gis/forms-api/#widget-classes) may do this for us out of the box, but I'm not super confident in that.

**Comment by beamalsky** [comment]
This should create new instances of the PLDP [Location](https://github.com/datamade/django-pldp/blob/master/pldp/models/location.py) model
