### ISSUE TITLE
Deployment tasks

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#9]
We can handle some deployment tasks early on, mainly, spinning up a Just Spaces server (if we want to do this) and deploying a staging site. 

Before starting this issue, I'll touch base with the DevOps team re: https://github.com/datamade/devops/issues/66

**Comment by reginafcompton** [comment]
We will deploy the Just Spaces staging site on the Staging server [(given our conversation during devops).](https://github.com/datamade/devops/issues/66#issuecomment-460327717)

@beamalsky - we're trying out [a new pattern for creating deployment scripts](https://github.com/datamade/deploy-a-site/pull/45): you'll be taking the freshly written documentation for a test drive! Follow the deploy-a-site documentation, as it appears in the [cookie-cutter branch](https://github.com/datamade/deploy-a-site/tree/cookiecutter). @hancush will look forward to any feedback you have!

**Comment by beamalsky** [comment]
Exciting !!
