### ISSUE TITLE
Templated surveys

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#90]
Our mockups suggest that we'll offer users the choice between creating a new survey from scratch and creating one from a "template". I don't think this is a required feature for the MVP, but I think it could be potentially very useful and I want to make sure that we keep track of it.

**Comment by beamalsky** [comment]
We're doing this! 

When creating a new survey, users should be able to load a template with preset questions.

We'll wait on UCD to create these sample surveys on the staging site and copy them into templates. There may be different templates for Intercept and Observational surveys.
